### ISSUE TITLE
HardWareSerial::flush method is not compatible Arduino Library.

### ISSUE THREAD

**Issue by masato-ka** [Seeed-Studio/stm32f4ArduinoCore#1]
The HardWareSerial::flush method is behavior of waiting transmit data in case of original Arduino Library. However, The function is reset rx buffer in case of Seeed_STM32F4 Arduino Library.
 Actually, the function reset rx buffer in old version Arduino API behavior. But now it changed.
  If you use Library that using HardwareSerial, Perhaps Unexpected behavior may occur. I think that it is better to modify the behavior of the function or describe the user document.
 Please consider that.
https://www.arduino.cc/en/Serial/Flush

https://github.com/Seeed-Studio/Seeed_STM32F4/blob/38af1805dbc4c6da3cd0dab44dc9dd119a1d6d3e/cores/arduino/HardwareSerial.cpp#L159

Best Regards

**Comment by KillingJacky** [comment]
Hi @masato-ka , the issue is a real one, already marked with to-be-fixed😀

**Comment by lanselambor** [comment]
@masato-ka 
After reading this forum - [Arduino for STM32](http://www.stm32duino.com/viewtopic.php?t=1112)
I think the flush method is good to be waiting for TX to finish rather than to set RX buffer.
I will update this right now.

**Comment by masato-ka** [comment]
Thank you for your response. I waiting for release :) .

**Comment by lanselambor** [comment]
@masato-ka This modification has been updated in Seeed_STM32F4_v1.1.3.tar.bz2

**Comment by masato-ka** [comment]
Thank you. I confirm below repository.
https://github.com/Seeed-Studio/Seeed_Platform/blob/master/Seeed_STM32F4_v1.1.3.tar.bz2
very helpful.
